#openscad endcap.scad -D part=0 -o dxf/end_plate.dxf >/dev/null 2>/dev/null & 
openscad endcap.scad -D part=1 -o dxf/support_plate.dxf >/dev/null 2>/dev/null &
openscad endcap.scad -D part=11 -o dxf/support_plate_holed.dxf >/dev/null 2>/dev/null &
#openscad endcap.scad -D part=12 -o dxf/support_plate_cover.dxf >/dev/null 2>/dev/null &
#openscad endcap.scad -D part=2 -o dxf/cross_plate.dxf >/dev/null 2>/dev/null &
#openscad endcap.scad -D part=3 -o dxf/vertical_wall_plate.dxf >/dev/null 2>/dev/null
openscad endcap.scad -D part=4 -o dxf/top_wall_plate_motor.dxf >/dev/null 2>/dev/null &
openscad endcap.scad -D part=5 -o dxf/top_wall_plate_idler.dxf >/dev/null 2>/dev/null &
openscad endcap.scad -D part=6 -o dxf/bottom_wall_plate.dxf >/dev/null 2>/dev/null &
#openscad endcap.scad -D part=61 -o dxf/bottom_wall_support_plate_.dxf >/dev/null 2>/dev/null &
#openscad endcap.scad -D part=7 -o dxf/corner_plate.dxf >/dev/null 2>/dev/null &
#openscad endcap.scad -D part=71 -o dxf/corner_plate_support.dxf >/dev/null 2>/dev/null &
